spring:
  profiles:
    active:
      - authserver
      - local

#logging:
#  level:
#    org.springframework.security: trace

springdoc:
  swagger-ui:
    operationsSorter: alpha

---
spring:
  config:
    activate:
      on-profile:
        - local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          #jwk-set-uri: ${azure.login-url}/${azure.tenant}/discovery/v2.0/keys
          #issuer-uri: http://127.0.0.1:8080
          jwk-set-uri: http://127.0.0.1:8080/oauth2/jwks
          audiences: app-client

# For debugging purposes
management:
  endpoints:
    web:
      exposure:
        include: "*"

  
# See https://127.0.0.1:8443/.well-known/openid-configuration
app:
  security:
    authority: https://127.0.0.1:8443
    knownAuthorities:
      - https://127.0.0.1:8443
    protocolMode: OIDC
    clientId: app-client
    scopes:
      - openid
    redirectUri: https://localhost:8443
    postLogoutRedirectUri: https://127.0.0.1:8443/oauth2/logged-out
  ldap:
    url: ldap://localhost:8389/dc=example,dc=org
  swagger:
    oauth2:
      authorization-uri: https://127.0.0.1:8443/oauth2/authorize
      token-uri: https://127.0.0.1:8443/oauth2/token